---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
#     - name: Ensures taps are present via homebrew
#       community.general.homebrew_tap:
#         name: "{{ item }}"
#         state: present
#       with_items:
#         - hashicorp/tap
    - name: Ensures packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        install_options: appdir=/Applications
      with_items:
        - karabiner-elements
        - 1password
        - ansible
        - iterm2
        - alacritty
        - ansible
    - name: Ensures packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        path: /Applications
        state: present
      with_items:
        - openssl
        - atuin
        - chezmoi
        - 1password-cli
        - xz
        - zlib
        - wget
        - fzf
        - ansible-lint
        - ranger
        - bat
        - btop
        - readline
        - ca-certificates
        - eza
        - lpeg
        - fzf
        - fd
        - luajit
        - stow
        - gettext
        - luv
        - tlrc
        - gh
        - git
        - tree
        - tmux
        - ncurses
        - tree-sitter
        - htop
        - neovim
        - unibilium
        - lazygit
        - zoxide
        - zsh-syntax-highlighting
      ignore_errors: yes
      tags:
        - packages
